services:
  node:
    build:
      context: ../api-backend
      dockerfile: ../docker/current_build.dockerfile
    ports:
      -"8888:8888"
    environment: 
      MYSQL_HOST: db
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pawse

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: